version: "3"

services:
    bot:
        image: silk:latest
        build: .
        volumes:
            - ./config:/silk/SilkBot/ServerConfigs
            - ./Token.txt:/silk/Token.txt
            - C:\Users\Cinnamon\AppData\Roaming\SilkBot:/silk/SilkBot